# Generated by Django 2.1.3 on 2018-12-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('nro_folio', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_ascensor', models.CharField(max_length=20)),
                ('modelo_ascensor', models.CharField(max_length=20)),
                ('fallas_detectadas', models.CharField(max_length=200)),
                ('reparaciones', models.CharField(max_length=200)),
                ('piezas_cambiadas', models.CharField(blank=True, max_length=200)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('tecnico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Usuario')),
            ],
        ),
    ]
