# Generated by Django 2.1.4 on 2018-12-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=120)),
                ('contraseña', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('tecnico', 'Tecnico'), ('administrador', 'Administrador')], default='tipo usuario', max_length=50)),
            ],
        ),
    ]
